# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "chess"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "chess"
region = "us-east-1"
parameter_overrides = "ApiGatewayCloudWatchRoleArn=\"arn:aws:iam::708746137251:role/allow-api-gateway-to-push-to-cloudwatch-logs\" GameTableName=\"game\" UserTableName=\"user\" UserTableGsi=\"find-games-upon-disconnect\" GitHubRepositoryOwner=\"brendandagys\" Repository=\"chess\" Branch=\"main\" CreateDeployBucketAndPolicy=\"true\" Domain=\"chess.brendandagys.com\" DnsRecordWwwFlag=\"false\" BedrockModelId=\"us.anthropic.claude-3-5-haiku-20241022-v1:0\" DistributionHomePage=\"/index.html\" CloudFrontHostedZoneId=\"Z2FDTNDATAQYW2\" CloudFrontCachePolicy=\"658327ea-f89d-4fab-a63d-7e88639e58f6\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
